In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# 1. Python

**Task 1** (0.5 points)<br/> 
Enter numbers `a`,  `d` и `N`. Find sum of the first `N` members of arithmetic progression with the first member `a` and difference `d`, without using formula for the sum.

In [13]:
a = int(input("Enter a: "))
d = int(input("Enter d: "))
N = int(input("Enter N: "))

ary_sum = 0
for i in range(N):
    ary_sum += a
    a += d
    
ary_sum

Enter a: 1
Enter d: 2
Enter N: 3


9

**Task 2** (0.5 points) <br/> 
Enter a number `N`. Find sum of the first `N` memebers of harmonic series.

In [15]:
N = int(input("Enter N: "))

harm_sum = 0

for i in range(N):
    harm_sum += (1 / (i + 1))
    
harm_sum

Enter N: 3


1.8333333333333333

**Task 3** (0.5 points) <br/> 
Enter an integer number `N`. Check if it is a prime number.

In [63]:
def IsNumberPrime(N):
    if (N <= 0):
        return

    is_prime = True

    # if we cant import any other libraries than those that are connected
    # in the start of this doc, then i'll use N/2 and not sqrt(N)
    for i in range(2, round(N / 2) + 1):
        if (N % i == 0):
            is_prime = False

    if (is_prime):
        return True
    else:
        return False
    
print('Is your input number prime? - ', IsNumberPrime(int(input('Enter N: '))))

Enter N: 5
Is your input number prime? -  True


**Task 4** (0.5 points) <br/> 
Enter the first `N` prime numbers.

In [75]:
N = int(input('Enter N: '))

i = 1
while (N != 0):
    if (IsNumberPrime(i)):
        print(i)
        N -= 1
    i += 1

Enter N: 5
1
2
3
5
7


**Task 5** (0.5 points) <br/> 
There are numbers: `a`, `b`, `c`. Without using functions `min`, `max` and other functions, find the maximum number.

In [79]:
a = 10
b = 13
c = 11

def findMax(a, b, c):
    if (a > b):
        if (a > c):
            return a
        else:
            return c
    else:
        if (b > c):
            return b
        else:
            return c
        
findMax(a,b,c)

13

# 2. Numpy

**Task 1** (0.5 points) <br/>
Create two random arrays $a$ and $b$ with the same length. 

Calculate the following distances between the arrays:

* Euclidean Distance
$$ d(a, b) = \sqrt{\sum_i (a_i - b_i)^2} $$
* Manhattan Distance
$$ d(a, b) = \sum_i |a_i - b_i| $$
* Cosine Distance
$$ d(a, b) = 1 - \frac{a^\top b}{||a||_2\cdot||b||_2}$$


In [25]:
length = 10
a = np.random.rand(length)
b = np.random.rand(length)

print('Euclidean: ', np.sqrt(np.sum((a - b) ** 2, axis = 0)))
print('Manhattan: ', np.sum(abs(a - b), axis = 0))
print('Cosine: ', np.sum(a*b) / (np.sqrt(np.sum(a**2)) * np.sqrt(np.sum(b**2))) )

Euclidean:  0.9570479993547552
Manhattan:  2.54971568419656
Cosine:  0.8851566839208176


**Task 2** (0.5 points) <br/>
Create a random array (`np.random.rand()`) with length of 10 and with sum of its elements equals to 2.

In [39]:
arr = np.random.rand(10)
arr_sum = np.sum(arr)
new_arr = [x * 2 / arr_sum for x in arr]

round(np.sum(new_arr))

2.0

**Task 3** (0.5 points) <br/>
Create a random array (`np.random.rand()`) with length of 100. Transform the array so, that 
* Maximum element(s) value is 1
* Minimum element(s) value is 0
* Other values are in interval 0-1 with keeping the order

In [76]:
# Hard to understand what result task is wanting to see
# I'm replacing max with 1, min with 1 and sorting array. Hope this is what You want to see

arr = np.random.rand(100)
# finding array of indeces of minimum elements (not only one because several min can be generated)
arr_min_index = np.where(arr == arr.min())[0]
arr_max_index = np.where(arr == arr.max())[0]

# replacing
for ind in arr_min_index:
    arr[ind] = 0
for ind in arr_max_index:
    arr[ind] = 1

# sorting
arrS = np.sort(arr)
arrS

array([0.        , 0.03590957, 0.04371513, 0.04397114, 0.04478759,
       0.04911271, 0.05444057, 0.06068691, 0.08429856, 0.10110247,
       0.10330077, 0.10615784, 0.11642843, 0.12694164, 0.12829094,
       0.13080134, 0.13380989, 0.13615827, 0.1382083 , 0.14282072,
       0.14843136, 0.16131891, 0.21886692, 0.21917933, 0.22002036,
       0.22325979, 0.22474764, 0.23001655, 0.23792853, 0.25211198,
       0.26250964, 0.28144132, 0.28639913, 0.29316538, 0.3081253 ,
       0.32217357, 0.32695895, 0.3332247 , 0.34666168, 0.36062344,
       0.37126371, 0.37207513, 0.37534269, 0.40628011, 0.43795745,
       0.45796474, 0.47441196, 0.47505487, 0.47791206, 0.48255594,
       0.49632534, 0.51721368, 0.51869485, 0.52580504, 0.53051864,
       0.5412917 , 0.54781182, 0.55265606, 0.56201802, 0.57678729,
       0.61936088, 0.62705649, 0.62746111, 0.65157179, 0.66447815,
       0.68495159, 0.69516771, 0.72571654, 0.73011117, 0.73697671,
       0.77656247, 0.7945893 , 0.79995294, 0.80292666, 0.80729

**Task 4** (0.5 points) <br/>
Create a random array with length of 20 with integers from [0,50]. Select elements that are smaller than 5th percentile and larger than 95th percentile

In [121]:
arr = np.sort(np.random.randint(0, 51, 20))
print(arr)

smalls = arr[arr < np.percentile(arr, 5)]
print(smalls)

bigs = arr[arr > np.percentile(arr, 95)]
print(bigs)

[ 0  3  4  6  6 11 13 16 16 17 25 25 27 32 37 39 45 45 47 49]
[0]
[49]


**Task 5** (0.5 points) <br/>
Create an array with shape of $5 \times 6$ with integer from [0,50]. Print a column that contains the maximum element of the array.

In [134]:
arr = np.random.randint(0, 51, size=(5, 6))
print(arr)
print('column with max elem: ', arr[:,arr.argmax() % 6])

[[17 42 21 50  1  9]
 [39  2 13 41 18  1]
 [34 32 39 42 39 46]
 [ 6 25 31  9 43 42]
 [31 22 44 33  8 46]]
column with max elem:  [50 41 42  9 33]


**Task 6** (0.5 points) <br/>

Replace all missing values in the following array with mean.

In [152]:
arr = np.random.rand(10)
idx = np.random.randint(0, 10, 4)
arr[idx] = np.nan
print(arr)

# my code starts here
arr[np.isnan(arr)] = np.mean(arr[np.logical_not(np.isnan(arr))])
print(arr)

[0.18430574 0.6620931  0.87621668 0.54612538        nan 0.90761592
        nan        nan        nan 0.58264642]
[0.18430574 0.6620931  0.87621668 0.54612538 0.62650054 0.90761592
 0.62650054 0.62650054 0.62650054 0.58264642]


In [13]:
## Your code here

### Linear Regression

Download [file 1](https://www.dropbox.com/s/kg9px9v3xfysak9/tutorial_dataset.csv?dl=0) and [file 2](https://www.dropbox.com/s/f87gm612o144emx/tutorial_dataset_2.csv?dl=0) into a directory with this notebook. Using function `loadtxt` in `numpy` load data from the first file. Assign y = D[:,0] аnd X = D[:, 1:].


We will use one magic formula to find linear regression coefficients. You will prove this formula on your next lectures of the course.

Linear regression model in matrix form looks like: $\hat{y} = X\hat{\beta}$, where

$$ \hat{\beta} = (X^\top X)^{-1} X^\top y $$
Model residuals are calculated as
$$ \text{res} = y - \hat{y} $$


**Task 7** (2.5 points)<br/>
1. Load the data
2. Find parameters $\hat{\beta}$ using the formula above
3. Make a plot with the model residuals on Y axis and $\hat{y}$ on X axis

In [14]:
## load data
D = np.loadtxt('tutorial_dataset.csv', 
               skiprows=1, 
               delimiter=',')

## Your code here

# 3. Pandas

### Wine Quality

Download [sample](https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv) with information about wine characteristics and its quality.

In [15]:
## Your code here

**Task 1 ** (1 point) <br/>
* How much objects are in the sample?
* What features describe the objects? How much these features?
* What is feature a target variable?
* What are their ranges?
* Are there any missing values?

In [16]:
## Your code and answers here

**Task 2** (1 point)<br/>
What features affect the target variable the most?

In [17]:
## Your code here